resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/25.yaml

packages: 
 - tree-sitter

system-ghc: true

extra-include-dirs:
 - /opt/homebrew/Cellar/tree-sitter/0.22.6/include
